version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "5555:5555"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

networks:
  default:
    driver: bridge 